CREATE TABLE SYSTEM_CONFIGURATION_GROUP
(
    ID          CHAR(36)     NOT NULL DEFAULT UUID() PRIMARY KEY UNIQUE,
    NAME        VARCHAR(200) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(200),
    ACTIVE      BOOL         NOT NULL DEFAULT TRUE
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8;

INSERT INTO SYSTEM_CONFIGURATION_GROUP (ID, NAME, DESCRIPTION, ACTIVE)
VALUES ('53fa779d-a73c-4a28-a2c4-19bb2b5693c9', 'MINIO', 'Minio configurations', 1);

CREATE TABLE SYSTEM_CONFIGURATION
(
    ID                            CHAR(36)     NOT NULL DEFAULT UUID() PRIMARY KEY UNIQUE,
    ID_SYSTEM_CONFIGURATION_GROUP CHAR(36)     NOT NULL,
    FOREIGN KEY (ID_SYSTEM_CONFIGURATION_GROUP) REFERENCES SYSTEM_CONFIGURATION_GROUP (ID),
    DESCRIPTION                   VARCHAR(200),
    REFERENCE                     VARCHAR(200) NOT NULL UNIQUE,
    "VALUE"                         VARCHAR(200) NOT NULL,
    ACTIVE                        BOOL         NOT NULL DEFAULT TRUE
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8;

INSERT INTO SYSTEM_CONFIGURATION (ID, ID_SYSTEM_CONFIGURATION_GROUP, DESCRIPTION, REFERENCE, "VALUE", ACTIVE)
VALUES ('8f5f7916-2474-4feb-bec0-4dd5e19d2887', '53fa779d-a73c-4a28-a2c4-19bb2b5693c9',
        'Minio - Temporary bucket expiration in days', 'MINIO_TEMPORARY_BUCKET_EXPIRATION_IN_DAYS', '10', 1);